### ISSUE TITLE
Hi,

### ISSUE THREAD

**Issue by fenghuijian** [atarashansky/self-assembling-manifold#14]

**Comment by atarashansky** [comment]
Hello!

**Comment by fenghuijian** [comment]
Hi,
I have some questions about Sam algorithm.
When you call function PCA, do you input all the genes that are weighted? Are the 0 weight genes filtered out? and how many PCs did you take for clustering and umap visualization? 
Can I adjust these parameters about selecting the geng input and numbers of PCs

**Comment by atarashansky** [comment]
Hello!

In the original implementation of the algorithm, each iteration, I call PCA on all genes that are weighted. The 0 weight genes are automatically filtered out by virtue of them having zero weight (the weights are multiplied into the expression matrix prior to running PCA).

To avoid the arbitrariness of deciding how many PCs to take, I made a modification where I include all principal components and scale them by the amount of variance they explain. In other words, PCs that explain a lot of variance will be highly weighted and vice-versa (I think I refer to this approach in the paper as "weighted PCA").

So, in short, I include all genes and all PCs and instead scale each gene / PC by their SAM weight / explained variance, respectively.

However, in order to increase computational efficiency for larger datasets, I only keep the top 3000 weighted genes for PCA. Similarly, I only take the top 150 weighted PCs for UMAP. This does not seem to change the results that much since genes beyond the top 3000 typically have relatively small weights. Same for the PCs.

Finally, if the default parameters aren't working for you (which is quite rare in my experience) these parameters can be adjusted in the `run` function. The `n_genes` argument controls how many of the top-weighted genes to include for PCA (3000 for large datasets). `npcs` controls how many of the top-weighted PCs to include for UMAP visualization (150 for large datasets). 

If you would like to turn off "weighted PCA" and take a smaller subset of the original, unscaled principal components (lets say 25) for constructing the nearest neighbor graph in each iteration of SAM, then you can set the `weight_PCs=False` and `npcs=25`.

I would recommend leaving all parameters to be default settings as changing them does not dramatically change the results in my testing (except in rare cases). Hopefully this answers your questions! Let me know if you have any more questions.

**Comment by fenghuijian** [comment]
Thank you for your reply!
I tried to change `run` function `n_genes`, but the `sam.run` throw the error : TypeError: run() got an unexpected keyword argument 'n_genes'

**Comment by atarashansky** [comment]
Ah! Did you install SAM from pip? Until just now, pip was version 0.4.9 but I added in the n_genes argument in version 0.5.1.

The most up-to-date version of SAM is 0.5.1 (pip should also be updated to this version just now).

Please keep in mind that in version 0.5.1 some things have changed, namely how to visualize the results. The scatter function is now outside the SAM class and launches a GUI (graphical user interface) that allows you to interactively explore the data / highlight cells / zoom in,out / subcluster / etc. I'm still working on a tutorial for that but hopefully it's somewhat self-explanatory...

```
from SAM import SAM, scatter

sam=SAM()
# do your SAM things...

#launch the scatter plot
scatter(sam)
```

**Comment by fenghuijian** [comment]
oops！my SAM version is 0.4.9，I need to update the SAM.

**Comment by fenghuijian** [comment]
Thank you for your reply!

**Comment by atarashansky** [comment]
I hope this method is useful for you!

Also, I just added a (still incomplete) quick guide on the readme for how to navigate the GUI that you launch with the `scatter` function if that's something you're interested in!

**Comment by fenghuijian** [comment]
In my opinion, this paper uses the k nearest neighbor, weight and iteration method to calculate high-weight genes, which is superior to HVG of single cell.
Now it is difficult to provide important information for my research by using seurat's HVG method, even though I use their latest normalized method  `sctransfrom`.
So I also hope this method is useful for me.

**Comment by atarashansky** [comment]
Let me know if you need any specific suggestions! I'd be more than happy to give feedback. Best,

**Comment by fenghuijian** [comment]
Hi,
when I use the sam0.5.2 for running the `scatter(sam)`, it throws the error `:matplotlib not insatlled` , or
whne I run  `from SAM import scatter`, it throw the error `matplotlib not installed. Plotting functions disabled`. But I can run `import matplotlib` perfectly. How to solve this problem.

**Comment by atarashansky** [comment]
Hi Feng,

The dependencies for plotting capabilities in SAM changed. Please install:

`pip install pyperclip`
`pip install PyQt5`

If that still doesn't work for you, the original `sam.scatter` function I had in verisons < 0.5.0 is still available for now.

Best,

**Comment by atarashansky** [comment]
Closing this for now -- feel free to reopen if you have any other questions.
