### ISSUE TITLE
issue about the sam.run()

### ISSUE THREAD

**Issue by nkm47** [atarashansky/self-assembling-manifold#27]
Hello,
I use the quickstart_guide.ipynb to run pipeline, and i get a wrong.  The matrix I use is from cellranger and seurat v3,  and it is a count matrix.
The wrong like this:
```
sam.load_data('./new-sir.csv')
# Preprocess the data
sam.preprocess_data()
# Run SAM
sam.run()
sam.scatter()
```
> ---------------------------------------------------------------------------
> RUNNING SAM
> Iteration: 0, Convergence: 0.31437060605776845
> TypeError                                 Traceback (most recent call last)
> <ipython-input-33-99b94e5586c4> in <module>
>       1 sam.preprocess_data()
>       2 # Run SAM
> ----> 3 sam.run()
>       4 sam.scatter()
> 
> ~/miniconda3/envs/environment_name/lib/python3.6/site-packages/samalg/__init__.py in run(self, max_iter, verbose, projection, stopping_condition, num_norm_avg, k, distance, preprocessing, npcs, n_genes, weight_PCs, sparse_pca, proj_kwargs)
>    1014 
>    1015             W, wPCA_data, EDM, = self.calculate_nnm(
> -> 1016                 n_genes, preprocessing, npcs, nnas, weight_PCs, sparse_pca,
>    1017             )
>    1018             new = W
> 
> ~/miniconda3/envs/environment_name/lib/python3.6/site-packages/samalg/__init__.py in calculate_nnm(self, n_genes, preprocessing, npcs, num_norm_avg, weight_PCs, sparse_pca, update_manifold)
>    1117 
>    1118         if update_manifold:
> -> 1119             edm = ut.calc_nnm(g_weighted, k, distance)
>    1120             self.adata.uns["nnm"] = edm
>    1121             EDM = edm.copy()
> 
> ~/miniconda3/envs/environment_name/lib/python3.6/site-packages/samalg/utilities.py in calc_nnm(g_weighted, k, distance)
>     448     if g_weighted.shape[0] > 8000:
>     449         # only uses cosine
> --> 450         nnm, dists = nearest_neighbors(g_weighted, n_neighbors=k, metric=distance)
>     451         EDM = gen_sparse_knn(nnm, dists)
>     452         EDM = EDM.tocsr()
> 
> ~/miniconda3/envs/environment_name/lib/python3.6/site-packages/samalg/utilities.py in nearest_neighbors(X, n_neighbors, metric, metric_kwds, angular, seed, low_memory)
>     175             leaf_array=leaf_array,
>     176             n_iters=n_iters,
> --> 177             verbose=False,
>     178         )
>     179 
> 
> TypeError: some keyword arguments unexpected

I find that, the matix is 26545 genes and 9462 cells, it get wrong with sam.run();
But if i cut a part of this matrix, like the first 1000 genes and first 3000 cells, the matrix(1000 x 3000) have no wrong with sam.run(). I do not know why? Or is this a bug?  Or there are some parameter can solve it?
 Looking forward to your reply, and excuse my poor English.

**Comment by atarashansky** [comment]
Hmm, this isn’t the first time I’ve seen this issue lately. It looks like some dependency may have gotten updated and is breaking something.

What version is numba?

**Comment by atarashansky** [comment]
I'm trying to reproduce this error with a fresh install and I cannot. Can you give me the version numbers of all the packages when you do `conda list`?

**Comment by atarashansky** [comment]
I fixed this issue!

It should be all good in version 0.7.2. Please update using either pip or github. Let me know if there are any other problems.

**Comment by nkm47** [comment]
> I fixed this issue!
> 
> It should be all good in version 0.7.2. Please update using either pip or github. Let me know if there are any other problems.

Thanks for your fast and efficient action to solve this problem. Now i can  run  sam.run().  successfully with a big matrix.
Thank you very much!

**Comment by nkm47** [comment]
Hi, now i have another question. I want to integrate three samples, and I have used seurat v3 IntegrateData() and export a integrated matrix( loged and scaled ,2000 genes and 28627 cells). The matrix like this
```
                TTTGCGCAGGCAAAGA_3    TTTCCTCAGGGTCGAT_3    TTGCGTCTCTGCTGTC_3   TTGCCGTAGTCAATAG_3
SMED30021196	7.681424e-02	0.0711096012	-9.943150e-02	-1.078620e-01
SMED30030310	-0.895603049	0.8488934158	8.862971e-01	1.801769e+00
SMED30007744	-1.664178e-01	0.8151612777	-6.103513e-03	1.178678e+00
```
If i want to use sam.preprocess_data() and sam.run()  to find some good selected features, could SAM deal with the scaled matrix? Or are there a better method to integrete three big samples( two 10x and one dropseq dataset ). 
Thanks for you!

**Comment by atarashansky** [comment]
Hi, that's a good question. Because you've already preprocessed the data with Seurat, and there are negative values, you should not run `sam.preprocess_data()` again. You can just go ahead and use `sam.run()`.

Although, for a large dataset such as yours, I would recommend you try the following parameters:
`sam.run(preprocessing='StandardScaler',weight_PCs=False,npcs=150)` You can look at the tutorial to see what these parameters are doing, but I've found they work best on big datasets where you expect many cell types.

Now, running SAM on integrated datasets is tricky as these datasets have negative values. The way SAM calculates its weights is by calculating something similar to a dispersion score (variance / mean) for each gene. Dispersion is only a meaningful measure on non-negative data. There are two options to get around this:

Strategy 1:
a) Save the original combined expression data (log2 transformed, unscaled, not batch-corrected expression counts) to a file
b) Load the file into SAM.
c) Set sam.adata.X equal to the scaled, integrated matrix. 
d) Run SAM

This works because when you load data into SAM, the data is stored in both `sam.adata.X` and `sam.adata.layers['X_disp']`. SAM computes the dispersions from the `'X_disp'` layer, whereas SAM does dimensionality reduction on `sam.adata.X`, which you will set to the integrated matrix. Because the `'X_disp'` layer will be non-negative expression values, calculating the SAM weights will not be a problem anymore. This is something I've done before and it worked pretty well.

Strategy 2:
I added in a modification to the method just now. If SAM detects that your expression matrix has negative values, it will default to computing something more similar to the variance of each gene as opposed to the dispersion. Calculating variance on negative data isn't a problem.

In my opinion, I think (2) will not perform as well as (1), but you can give both a shot!

I just added the modifications mentioned in (2) to the github, so if you want to try that out please update to the latest version from the github repository (it isn't on pip yet).

Hope this answered your question!

**Comment by nkm47** [comment]
Thanks for your answer.
I have tried  sam.run(preprocessing='StandardScaler',weight_PCs=False,npcs=150), and it works. Now i want to extrat some selected gene that reback to seurat, could you give me some advice on thresholds to select genes?
Another  question is, the cellranger result is a count matrix, but the matrix you use is TPM or FPKM matrix, if i use a count matrix to deal  with sam.preprocess_data()  and sam.run() , whats the difference between them?
hope your answer, thanks!

**Comment by atarashansky** [comment]
TPM, FPKM, UMI counts, raw read counts, it all works! If you use a count matrix, I would recommend using `sam.preprocess_data(sum_norm='cell_median')` which ensures that each cell has the same number of counts.

**Comment by nkm47** [comment]
> TPM, FPKM, UMI counts, raw read counts, it all works! If you use a count matrix, I would recommend using `sam.preprocess_data(sum_norm='cell_median')` which ensures that each cell has the same number of counts.

Thanks a lot. It help very much.
