### ISSUE TITLE
compatibility with h5py

### ISSUE THREAD

**Issue by galicae** [atarashansky/self-assembling-manifold#40]
Dear Alex!

me and many other people are relying on SAM and SAMap for cross-species comparisons (thanks for that!), and installation is always an issue. Especially in conda environments, SAM and SAMap often cause version clashes. Is there anything you could do for that? Would it be possible to bump their version requirements so that the worst offenders (i.e. h5py) don't cause so many problems, or would that break the workflows?

best
Niko

**Comment by atarashansky** [comment]
Hi Niko,

Thanks for alerting me to this. The `h5py` pin used to be necessary due to past bugs in `AnnData`. 

I removed the `h5py` pin in both SAM (`pip install sam-algorithm==1.0.1`) and SAMap (`pip install samap==1.0.7`). I haven't tested this change, so keeping my fingers crossed that it doesn't break anything :'D

EDIT: just installed locally and was able to run through the tutorial notebook in SAMap...Seems like nothing exploded.

**Comment by atarashansky** [comment]
Closing for now, please re-open if there are still issues with the installation!

**Comment by galicae** [comment]
so far I have usually installed by local forks, where I removed the pin myself >.< seems to be working just fine.
